platform: linux

image_resource:
  type: docker-image
  source: 
    repository: golang
    tag: 1.8

inputs:
- name: plexdrive
  path: go/src/github.com/dweidenfeld/plexdrive

run:
  path: go/src/github.com/dweidenfeld/plexdrive/ci/build.sh

outputs:
- name: binary