resources:
- name: plexdrive
  type: git
  source:
    uri: https://github.com/dweidenfeld/plexdrive
    branch: master

jobs:
- name: test
  plan:
  - get: plexdrive
    trigger: true
  - task: test
    file: plexdrive/ci/test.yml
- name: deploy-artifacts
  plan:
  - get: plexdrive
    trigger: true
    passed: [test]
  - task: compile
    file: plexdrive/ci/build.yml
  - task: deploy
    file: plexdrive/ci/deploy.yml