resources:
- name: plexdrive
  type: git
  source:
    uri: https://github.com/dweidenfeld/plexdrive
    branch: master

jobs:
- name: build
  plan:
  - get: plexdrive
    trigger: true
  - task: test
    file: plexdrive/ci/test.yml
  - task: compile
    file: plexdrive/ci/build.yml