resources:
- name: plexdrive
  type: git
  source:
    uri: https://github.com/dweidenfeld/plexdrive
    branch: master

- name: gh-release
  type: github-release
  source:
    owner: dweidenfeld
    repository: plexdrive
    access_token: {{gh-access-token}}

jobs:
- name: build
  plan:
  - get: plexdrive
    trigger: true
  - task: test
    file: plexdrive/ci/test.yml
  - task: compile
    file: plexdrive/ci/compile.yml
  - put: gh-release
    params:
      name: plexdrive/docs/version
      tag: plexdrive/docs/version
      globs:
      - release/*

# - name: deploy-artifacts
#   plan:
#   - get: plexdrive
#     trigger: true
#     passed: [test]
#   - task: deploy
#     file: plexdrive/ci/deploy.yml