resources:
- name: plexdrive
  type: git
  source:
    uri: https://github.com/dweidenfeld/plexdrive
    branch: master

- name: github-nightly-release
  type: github-release
  source:
    owner: dweidenfeld
    repository: plexdrive
    access_token: {{gh-access-token}}
    release: false
    pre_release: true

jobs:
- name: build
  plan:
  - get: plexdrive
    trigger: true
  - task: test
    file: plexdrive/ci/test.yml
  - task: compile
    file: plexdrive/ci/compile.yml
  - put: github-nightly-release
    params:
      name: plexdrive/docs/version
      tag: plexdrive/docs/version
      globs:
      - release/*